'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OpenLayers_VBApp_skelton.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  var __map = null;
        '''var __view = null;
        '''var __baseLayer = null;
        '''
        '''function loadMap() {
        '''    if (typeof constantsInitialBaseLayer !== &apos;undefined&apos;) {
        '''        __baseLayer = getBaseLayer(constantsInitialBaseLayer);
        '''    } else {
        '''        __baseLayer = getBaseLayer(null);
        '''    };
        '''
        '''    __view = new ol.View({
        '''        projection: &quot;EPSG:3857&quot;,
        '''        center: ol.proj.transform([138.336744, 38.748977], &quot;EPSG:4326&quot;, &quot;EPSG:3857&quot;),
        '''        minZoom: 0,
        '''        maxZoom: 18,
        '''        zoom: 4.5
        '''    });
        '''
        '''    __map  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property createmap_js() As String
            Get
                Return ResourceManager.GetString("createmap_js", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  const __info = document.getElementById(&apos;info&apos;);
        '''var __currentfeature = null;
        '''const __displayFeatureInfo = function (feature) {
        '''    if (typeof feature !== &apos;undefined&apos;
        '''        &amp;&amp; feature.getProperties().label != null
        '''        &amp;&amp; feature !== __currentfeature) {
        '''
        '''        const pixel = __map.getPixelFromCoordinate(feature.getGeometry().getCoordinates());
        '''
        '''        __info.style.left = pixel[0] + 10 + &apos;px&apos;;
        '''        __info.style.top = pixel[1] + 10 + &apos;px&apos;;
        '''        __info.style.visibility = &apos;visible&apos;;
        '''     [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property detectclick_js() As String
            Get
                Return ResourceManager.GetString("detectclick_js", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  // マップ上に点を追加
        '''
        '''var __markerStyle = null;
        '''var __JSONStyle = null;
        '''var __JSONStyleFunc = null;
        '''var __featureLayer = null;
        '''var __geojsonSource = null;
        '''var __geojsonLayer = null;
        '''var __dragMoveFeatureInteraction = null;
        '''
        '''// 標準のマーカーのスタイルを設定
        '''function setMarkerStyle() {
        '''    if (__markerStyle === null) {
        '''        __markerStyle = {};
        '''        __markerStyle.defaultMarker = new ol.style.Style({
        '''            image: new ol.style.Icon({
        '''                anchor: [0.5, 1],
        '''                anchorXUnits: &apos;fractio [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property drawitems_js() As String
            Get
                Return ResourceManager.GetString("drawitems_js", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&apos;ja&apos;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&apos;UTF-8&apos; /&gt;
        '''    &lt;title&gt;地図表示&lt;/title&gt;
        '''    &lt;meta name=&quot;description&quot; content=&quot;地図表示のサンプル&quot; /&gt;
        '''    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdn.jsdelivr.net/npm/ol@v7.1.0/ol.css&quot; type=&quot;text/css&quot; /&gt;
        '''    &lt;script src=&quot;https://cdn.jsdelivr.net/npm/ol@v7.1.0/dist/ol.js&quot;&gt;&lt;/script&gt;
        '''    &lt;link rel=&quot;stylesheet&quot; href=&quot;style_css.css&quot; type=&quot;text/css&quot; /&gt;
        '''    &lt;script src=&quot;constantsBox.js&quot;&gt;&lt;/script&gt;
        '''    &lt;script src=&quot;constantsBaseLayer.js&quot;&gt;&lt;/script&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property index_html() As String
            Get
                Return ResourceManager.GetString("index_html", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property marker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  body {
        '''    margin: 0;
        '''    padding: 0;
        '''}
        '''
        '''#map {
        '''    position: absolute;
        '''    top: 0;
        '''    bottom: 0;
        '''    width: 100%;
        '''}
        '''
        '''#info {
        '''    position: absolute;
        '''    display: inline-block;
        '''    height: auto;
        '''    width: auto;
        '''    z-index: 100;
        '''    background-color: rgba(240, 240, 240, 0.8);
        '''    padding: 10px;
        '''    /* transform: translateX(3%); */
        '''    visibility: hidden;
        '''    pointer-events: none;
        '''} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property style_css() As String
            Get
                Return ResourceManager.GetString("style_css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  //地図の表示状態を取得
        '''var __zoomInfo = {
        '''    &quot;zoom&quot;: 0,
        '''    &quot;center&quot;: [0, 0],
        '''    &quot;extent&quot;: [0, 0, 0, 0]
        '''};
        '''
        '''function entryZoomEvent() {
        '''    __map.on(&apos;moveend&apos;, function () {
        '''        __moveFeatureInfo();
        '''        __zoomInfo.zoom = __view.getZoom();
        '''        __zoomInfo.center = ol.proj.transform(__view.getCenter(), &apos;EPSG:3857&apos;, &apos;EPSG:4326&apos;);
        '''        __zoomInfo.extent = ol.proj.transformExtent(
        '''            __view.calculateExtent(__map.getSize()), &apos;EPSG:3857&apos;, &apos;EPSG:4326&apos;);
        '''
        '''        var messages = [];
        '''    [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property zoommap_js() As String
            Get
                Return ResourceManager.GetString("zoommap_js", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
